#!/usr/bin/env python3
"""Export symbols and data types for Ghidra into ghidra/.

    python tools/decomp/export_ghidra.py [--version USA_1_5] [--analysis-dir DIR]

  ghidra/symbols/code_<version>.txt          names for code.elf     ("<name> <address> <f|l>"),
                                             including the hand named heap setup
  ghidra/symbols/cro/<Module>.txt            names inside each CRO  ("<name> <offset> f", offset
                                             relative to the start of the .cro file)
  ghidra/types/acnl_save.h                   save data structures as plain C for
                                             File > Parse C Source

--analysis-dir: directory with ghidra_symbols.txt (tools/analysis/analyze.py) and
manual_ghidra_symbols.txt (tools/analysis/manual_names.py), default build/analysis. Both are merged
into one file; without them the code symbols are kept.
"""
import argparse, glob, json, os, re, shutil

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', '..'))
GHIDRA = os.path.join(ROOT, 'ghidra')

SAVE_HEADERS = ['dSvCommon', 'dSvFgName', 'dSvFgCategory', 'dSvPersonalId', 'dSvMyDesign', 'dSvMail',
                'dSvPlayerFlags', 'dSvInitiative', 'dSvNpcRef', 'dSvPlayer', 'dSvNpc', 'dSvStrc', 'dSvHouse',
                'dSvMuseum', 'dSvTownFlags', 'dSvTown', 'dSvCensus', 'dSvShared', 'dSvGardenPlus']


def ghidra_name(name):
    """Ghidra symbol names: no parameters, '::' namespaces are fine"""
    n = name.split('(')[0] if '(' in name and not name.startswith('operator') else name
    return n.replace('(anonymous namespace)', 'anonymous').replace(' ', '')


def export_cro(version):
    out_dir = os.path.join(GHIDRA, 'symbols', 'cro')
    os.makedirs(out_dir, exist_ok=True)
    total = 0
    for p in sorted(glob.glob(os.path.join(ROOT, 'config', version, 'modules', '*.json'))):
        mod = json.load(open(p, encoding='utf-8'))
        lines, seen = [], set()
        for f in mod.get('functions', []):
            if f['offset'] in seen or not f.get('name'):
                continue
            seen.add(f['offset'])
            lines.append(f'{ghidra_name(f["name"])} 0x{f["offset"]:08X} f')
        for c in mod.get('classes', []):
            for vt in c.get('vtables', []):
                label = f'{ghidra_name(c["name"])}::vtable' + (f'_{vt["offset_to_top"]}' if vt['offset_to_top'] else '')
                if vt['offset'] not in seen:
                    seen.add(vt['offset'])
                    lines.append(f'{label} 0x{vt["offset"]:08X} l')
        with open(os.path.join(out_dir, mod['module'] + '.txt'), 'w', encoding='utf-8', newline='\n') as fp:
            fp.write('\n'.join(lines) + '\n')
        total += len(lines)
    print(f'cro symbols: {total} names in {out_dir}')


def export_types():
    """flatten the Sv headers into C that Ghidra's parser accepts"""
    out = ['/* ACNL save data (garden_plus.dat) - generated by tools/decomp/export_ghidra.py.',
           '   Load in Ghidra with File > Parse C Source (pack 1 is required). */', '',
           'typedef unsigned char u8;', 'typedef unsigned short u16;', 'typedef unsigned int u32;',
           'typedef unsigned long long u64;', 'typedef signed char s8;', 'typedef short s16;', 'typedef int s32;',
           'typedef long long s64;', 'typedef unsigned short char16;', 'typedef u64 SvEncValue;', 'typedef s64 SvTime;',
           '', '#pragma pack(push, 1)', '',
           'typedef struct SvFgName {', '    u16 id; /* SvFgName::Name, 0x7FFE = empty */', '    u16 flags;', '} SvFgName;', '']
    for h in SAVE_HEADERS:
        if h == 'dSvFgName':
            continue
        text = open(os.path.join(ROOT, 'include', 'Sv', h + '.h'), encoding='utf-8').read()
        text = re.sub(r'#pragma once|#include[^\n]*|#pragma pack\([^)]*\)|ASSERT_SIZE\([^)]*\);', '', text)
        text = re.sub(r'typedef [^;]*(SvEncValue|SvTime);', '', text)
        text = re.sub(r'static const u32 (\w+)\[\d+\] = \{[^}]*\};', '', text)
        # "struct X { enum Name { ... }; };" -> "typedef enum X { ... } X;"
        # (C has one scope for enumerators: prefix them with the enum name)
        text = re.sub(r'struct (\w+) \{\s*enum Name \{(.*?)\};\s*\};',
                      lambda m: f'typedef enum {m.group(1)} {{' +
                      re.sub(r'^(\s+)(\w+) =', lambda e: f'{e.group(1)}{m.group(1)}_{e.group(2)} =',
                             m.group(2), flags=re.M) + f'}} {m.group(1)};', text, flags=re.S)
        text = re.sub(r'struct (\w+) \{', r'typedef struct \1 {', text)
        text = re.sub(r'(typedef struct (\w+) \{.*?\n)\};', r'\1} \2;', text, flags=re.S)
        text = re.sub(r'\bbool\b', 'u8', text)
        out.append(f'/* ---- {h}.h ---- */')
        out.append(re.sub(r'\n{3,}', '\n\n', text).strip() + '\n')
    out += ['#pragma pack(pop)', '']
    path = os.path.join(GHIDRA, 'types', 'acnl_save.h')
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as fp:
        fp.write('\n'.join(out))
    print('types:', os.path.relpath(path, ROOT))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--version', default='USA_1_5')
    ap.add_argument('--analysis-dir', default=os.path.join(ROOT, 'build', 'analysis'))
    a = ap.parse_args()
    sym_dir = os.path.join(GHIDRA, 'symbols')
    os.makedirs(sym_dir, exist_ok=True)
    # one file: the analysis names, then the hand named ones it does not have
    lines, seen = [], set()
    for src in ('ghidra_symbols.txt', 'manual_ghidra_symbols.txt'):
        p = os.path.join(a.analysis_dir, src)
        if not os.path.exists(p):
            continue
        for line in open(p, encoding='utf-8'):
            parts = line.split()
            if len(parts) == 3 and parts[1] not in seen:
                seen.add(parts[1])
                lines.append(line.rstrip('\n'))
    if lines:
        dst = f'code_{a.version}.txt'
        with open(os.path.join(sym_dir, dst), 'w', encoding='utf-8', newline='\n') as fp:
            fp.write('\n'.join(lines) + '\n')
        print('symbols:', dst)
    export_cro(a.version)
    export_types()


if __name__ == '__main__':
    main()
