#!/usr/bin/env python3
"""Export symbols and data types for Ghidra into ghidra/.

    python tools/decomp/export_ghidra.py [--version 0004000000086300] [--analysis-dir DIR]

  ghidra/symbols/code_<version>.txt          names for code.elf     ("<name> <address> <f|l>"),
                                             including the hand named heap setup
  ghidra/symbols/cro/<Module>.txt            names inside each CRO  ("<name> <offset> f", offset
                                             relative to the start of the .cro file)
  ghidra/types/acnl_save.h                   save data structures as plain C for
                                             File > Parse C Source

Function names come from config/<version>/symbols.json; the functions we decompiled take the name
of our source (check results in --build-dir, default build/gcc, so run check.py first).
--analysis-dir: directory with ghidra_symbols.txt (tools/analysis/analyze.py, for the typeinfo /
vtable labels) and manual_ghidra_symbols.txt (tools/analysis/manual_names.py, hand named globals),
default build/analysis. The globals of our sources ("// 0x..." comments) are added as well.
"""
import argparse, glob, json, os, re, shutil

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', '..'))
GHIDRA = os.path.join(ROOT, 'ghidra')

SAVE_HEADERS = ['dSvCommon', 'dSvFgName', 'dSvFgCategory', 'dSvPersonalId', 'dSvMyDesign', 'dSvMail',
                'dSvPlayerFlags', 'dSvInitiative', 'dSvNpcRef', 'dSvPlayer', 'dSvNpc', 'dSvStrc', 'dSvHouse',
                'dSvMuseum', 'dSvTownFlags', 'dSvTown', 'dSvCensus', 'dSvShared', 'dSvGardenPlus']


def ghidra_name(name):
    """Ghidra symbol names: no parameters, '::' namespaces are fine"""
    n = name.split('(')[0] if '(' in name and not name.startswith('operator') else name
    return n.replace('(anonymous namespace)', 'anonymous').replace(' ', '')


def export_cro(version):
    out_dir = os.path.join(GHIDRA, 'symbols', 'cro')
    os.makedirs(out_dir, exist_ok=True)
    total = 0
    for p in sorted(glob.glob(os.path.join(ROOT, 'config', version, 'modules', '*.json'))):
        mod = json.load(open(p, encoding='utf-8'))
        lines, seen = [], set()
        for f in mod.get('functions', []):
            if f['offset'] in seen or not f.get('name'):
                continue
            seen.add(f['offset'])
            lines.append(f'{ghidra_name(f["name"])} 0x{f["offset"]:08X} f')
        for c in mod.get('classes', []):
            for vt in c.get('vtables', []):
                label = f'{ghidra_name(c["name"])}::vtable' + (f'_{vt["offset_to_top"]}' if vt['offset_to_top'] else '')
                if vt['offset'] not in seen:
                    seen.add(vt['offset'])
                    lines.append(f'{label} 0x{vt["offset"]:08X} l')
        with open(os.path.join(out_dir, mod['module'] + '.txt'), 'w', encoding='utf-8', newline='\n') as fp:
            fp.write('\n'.join(lines) + '\n')
        total += len(lines)
    print(f'cro symbols: {total} names in {out_dir}')


def export_types():
    """flatten the Sv headers into C that Ghidra's parser accepts"""
    out = ['/* ACNL save data (garden_plus.dat) - generated by tools/decomp/export_ghidra.py.',
           '   Load in Ghidra with File > Parse C Source (pack 1 is required). */', '',
           'typedef unsigned char u8;', 'typedef unsigned short u16;', 'typedef unsigned int u32;',
           'typedef unsigned long long u64;', 'typedef signed char s8;', 'typedef short s16;', 'typedef int s32;',
           'typedef long long s64;', 'typedef unsigned short char16;', 'typedef u64 SvEncValue;', 'typedef s64 SvTime;',
           '', '#pragma pack(push, 1)', '',
           'typedef struct SvFgName {', '    u16 id; /* SvFgName::Name, 0x7FFE = empty */', '    u16 flags;', '} SvFgName;', '']
    for h in SAVE_HEADERS:
        if h == 'dSvFgName':
            continue
        text = open(os.path.join(ROOT, 'include', 'Sv', h + '.h'), encoding='utf-8').read()
        text = re.sub(r'#pragma once|#include[^\n]*|#pragma pack\([^)]*\)|ASSERT_SIZE\([^)]*\);', '', text)
        text = re.sub(r'typedef [^;]*(SvEncValue|SvTime);', '', text)
        text = re.sub(r'static const u32 (\w+)\[\d+\] = \{[^}]*\};', '', text)
        # "struct X { enum Name { ... }; };" -> "typedef enum X { ... } X;"
        # (C has one scope for enumerators: prefix them with the enum name)
        text = re.sub(r'struct (\w+) \{\s*enum Name \{(.*?)\};\s*\};',
                      lambda m: f'typedef enum {m.group(1)} {{' +
                      re.sub(r'^(\s+)(\w+) =', lambda e: f'{e.group(1)}{m.group(1)}_{e.group(2)} =',
                             m.group(2), flags=re.M) + f'}} {m.group(1)};', text, flags=re.S)
        text = re.sub(r'struct (\w+) \{', r'typedef struct \1 {', text)
        text = re.sub(r'(typedef struct (\w+) \{.*?\n)\};', r'\1} \2;', text, flags=re.S)
        text = re.sub(r'\bbool\b', 'u8', text)
        out.append(f'/* ---- {h}.h ---- */')
        out.append(re.sub(r'\n{3,}', '\n\n', text).strip() + '\n')
    out += ['#pragma pack(pop)', '']
    path = os.path.join(GHIDRA, 'types', 'acnl_save.h')
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as fp:
        fp.write('\n'.join(out))
    print('types:', os.path.relpath(path, ROOT))


OPS = {'()': 'call', '[]': 'index', '==': 'eq', '!=': 'ne', '=': 'assign',
       '<': 'lt', '>': 'gt', '<=': 'le', '>=': 'ge', '+': 'add', '-': 'sub',
       '*': 'mul', '/': 'div', '+=': 'add_assign', '-=': 'sub_assign',
       '++': 'inc', '--': 'dec', '!': 'not', '->': 'arrow', '<<': 'shl', '>>': 'shr'}


def sanitize(s):
    s = re.sub(r'\s*\[.*?\]', '', s)
    return re.sub(r'[^\w:~<>,*&]', '_', s.replace(' ', ''))


def split_qual(d):
    """'a::B<x::y>::f(int) const' -> ('a::B<x::y>', 'f')"""
    depth, i = 0, 0
    while i < len(d):
        if d[i] == '<':
            depth += 1
        elif d[i] == '>':
            depth -= 1
        elif d[i] == '(' and depth == 0 and not d[:i].endswith('operator'):
            break
        i += 1
    q = d[:i]
    parts, depth, last, j = [], 0, 0, 0
    while j < len(q):
        if q[j] == '<':
            depth += 1
        elif q[j] == '>':
            depth -= 1
        elif q.startswith('::', j) and depth == 0:
            parts.append(q[last:j])
            last = j + 2
            j += 1
        j += 1
    parts.append(q[last:])
    return '::'.join(parts[:-1]), parts[-1]


def func_name(label):
    """'ns::Cls::Meth(int, char) const [deleting]' -> 'ns::Cls::Meth_deleting' (same rules as
    tools/analysis/analyze.py, so names stay stable between exports); the this-adjusting thunks
    ('[thunk]', '[deleting thunk]') get '_thunk'"""
    deleting = '[deleting' in label
    thunk = 'thunk]' in label
    base = re.sub(r'\s*\[.*?\]', '', label).strip()
    # "(anonymous namespace)" would otherwise be taken for a parameter list
    base = base.replace('(anonymous namespace)', 'anonymous_namespace')
    # function templates demangle with their return type in front ("T* ns::f<T>(...)")
    head, depth, cut = base.split('(')[0], 0, -1
    for i, ch in enumerate(head):
        depth += ch == '<'
        depth -= ch == '>'
        if ch == ' ' and depth == 0 and not head.startswith('operator') and 'operator' not in head[:i]:
            cut = i
    if cut >= 0 and not base.startswith('thunk'):
        base = base[cut + 1:]
    if '(' in base:
        cls, meth = split_qual(base)
        if meth.startswith('operator'):
            op = meth[len('operator'):].strip()
            meth = 'operator_' + OPS.get(op, op.replace(' ', '_'))
        base = f'{cls}::{meth}' if cls else meth
    return sanitize(base) + ('_deleting' if deleting else '') + ('_thunk' if thunk else '')


def code_symbols(version, analysis_dir, build_dir):
    """function names: symbols.json (the same filter as analyze.py: no weak single-source names, no
    conflicts, no constructor guesses, no ICF stubs), replaced by the names of our decompiled
    functions (check results). Data: the RTTI labels of analyze.py, the hand named globals and the
    globals of our sources."""
    db = json.load(open(os.path.join(ROOT, 'config', version, 'symbols.json'), encoding='utf-8'))
    funcs = {}
    for f in db['functions']:
        note = f.get('note') or ''
        if (f['prio'] > 3 or f.get('tier') in ('C', 'X') or '[ctor?]' in f['name']
                or 'shared by' in note):
            continue
        # Thumb functions carry bit 0 in pointers; Ghidra places them at the even address
        funcs[f['addr'] & ~1] = func_name(f['name'])
    decompiled = 0
    res_path = os.path.join(build_dir, 'check', 'results.json')
    if os.path.exists(res_path):
        for k, r in json.load(open(res_path, encoding='utf-8'))['functions'].items():
            # stubs keep the symbols.json name; vf_0x.. placeholders are no better than it
            if not k.startswith('0x') or r['status'] == 'stub' or 'vf_0x' in r['name']:
                continue
            funcs[int(k, 16) & ~1] = func_name(r['name'])
            decompiled += 1
    else:
        print(f'note: {res_path} not found - run check.py first for the names of the decompiled code')
    lines = [f'{n} 0x{a:08X} f' for a, n in sorted(funcs.items())]

    data, seen = [], set(funcs)

    def add(name, addr):
        if addr not in seen:
            seen.add(addr)
            data.append(f'{name} 0x{addr:08X} l')
    for src in ('ghidra_symbols.txt', 'manual_ghidra_symbols.txt'):
        p = os.path.join(analysis_dir, src)
        if not os.path.exists(p):
            print(f'note: {p} not found')
            continue
        for line in open(p, encoding='utf-8'):
            parts = line.split()
            if len(parts) != 3:
                continue
            if parts[2] == 'l':
                add(parts[0], int(parts[1], 16))
            elif int(parts[1], 16) not in funcs:      # hand named functions symbols.json lacks
                funcs[int(parts[1], 16)] = parts[0]
                lines.append(line.strip())
    import check
    variables = sorted((a, n) for n, a in check.source_variables().items() if not n.startswith('guard '))
    for addr, name in variables:
        add(sanitize(name.replace('@anon', 'anonymous_namespace')), addr)
    print(f'code symbols: {len(funcs)} functions ({decompiled} from the decompiled sources), '
          f'{len(data)} data labels ({len(variables)} source globals)')
    return lines + data


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--version', default='0004000000086300')
    ap.add_argument('--analysis-dir', default=os.path.join(ROOT, 'build', 'analysis'))
    ap.add_argument('--build-dir', default=os.path.join(ROOT, 'build', 'gcc'))
    a = ap.parse_args()
    sym_dir = os.path.join(GHIDRA, 'symbols')
    os.makedirs(sym_dir, exist_ok=True)
    lines = code_symbols(a.version, a.analysis_dir, a.build_dir)
    dst = f'code_{a.version}.txt'
    with open(os.path.join(sym_dir, dst), 'w', encoding='utf-8', newline='\n') as fp:
        fp.write('\n'.join(lines) + '\n')
    print('symbols:', dst)
    export_cro(a.version)
    export_types()


if __name__ == '__main__':
    main()
