#!/usr/bin/env python3
"""Data blobs of the original that are not written as source (config/<version>/extracted_data.json).

    python tools/decomp/extract_data.py --check                       # every extern has an entry
    python tools/decomp/extract_data.py --output-dir build/gcc/extracted

The source declares such data as an extern variable with an address comment on the line above,

    // 0x009391A4
    extern const u8 s_DefaultComponent[];

and lists it in config/<version>/extracted_data.json. --check fails when a declaration has no
entry (or an entry has no declaration), so that no blob is forgotten. --output-dir copies the
bytes from orig/<version>/code.elf into <dir>/<name>.bin and writes <dir>/extracted_data.c, which
defines the symbols with .incbin (part of code.elf when it is linked, DECOMP_LINK=ON). Only the
user's own copy of the game is read; nothing of the original goes into the repository.
"""
import argparse
import glob
import json
import os
import re
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', '..'))
sys.path.insert(0, os.path.join(ROOT, 'tools', 'analysis'))
import elfmem  # noqa: E402

ADDRESS_RE = re.compile(r'//\s*0x([0-9A-Fa-f]{6,8})(?![0-9A-Fa-f])')
EXTERN_RE = re.compile(r'extern\s+(?!"C")[^;(]*?(\w+)\s*(\[[^\]]*\])?\s*;')


def load_blobs(version):
    path = os.path.join(ROOT, 'config', version, 'extracted_data.json')
    return json.load(open(path, encoding='utf-8'))['blobs']


def source_externs():
    """(address, unqualified name, file) of the extern variables with an address comment above."""
    out = []
    for d in ('src', 'lib', 'modules'):
        for path in glob.glob(os.path.join(ROOT, d, '**', '*.*'), recursive=True):
            if not path.endswith(('.cpp', '.c', '.h')):
                continue
            pending = None
            for line in open(path, encoding='utf-8', errors='replace'):
                st = line.strip()
                m = ADDRESS_RE.fullmatch(st.split(' (')[0]) if st.startswith('//') else None
                if m:
                    pending = int(m.group(1), 16)
                    continue
                if pending is not None and st and not st.startswith('//'):
                    e = EXTERN_RE.match(st)
                    if e:
                        out.append((pending, e.group(1), os.path.relpath(path, ROOT)))
                    pending = None
    return out


def check(blobs):
    by_address = {int(b['address'], 16): b for b in blobs}
    errors = []
    seen = set()
    for address, name, path in source_externs():
        blob = by_address.get(address)
        if blob is None:
            errors.append(f'{path}: extern {name} at 0x{address:08X} is not in extracted_data.json')
        elif blob['name'].split('::')[-1] != name:
            errors.append(f'{path}: extern {name} at 0x{address:08X} is called {blob["name"]} in extracted_data.json')
        seen.add(address)
    for address, blob in by_address.items():
        if address not in seen:
            errors.append(f'extracted_data.json: {blob["name"]} at 0x{address:08X} has no extern declaration in the source')
    return errors


def extract(blobs, version, output_dir):
    mem = elfmem.Mem(os.path.join(ROOT, 'orig', version, 'code.elf'))
    os.makedirs(output_dir, exist_ok=True)
    lines = ['/* generated by tools/decomp/extract_data.py from orig/%s/code.elf - do not edit */' % version]
    for blob in blobs:
        address = int(blob['address'], 16)
        size = int(blob['size'], 16)
        data = bytes(mem.mem[address - mem.base:address - mem.base + size])
        if len(data) != size:
            raise SystemExit(f'{blob["name"]}: 0x{address:08X} + 0x{size:X} is outside code.elf')
        bin_name = blob['symbol'] + '.bin'
        open(os.path.join(output_dir, bin_name), 'wb').write(data)
        bin_path = os.path.abspath(os.path.join(output_dir, bin_name)).replace('\\', '/')
        section = blob.get('section', '.rodata')
        flags = 'aw' if section == '.data' else 'a'
        lines += [
            f'/* {blob["name"]} (0x{address:08X}, 0x{size:X} bytes) */',
            '__asm__(',
            f'    ".section {section}.{blob["symbol"]}, \\"{flags}\\"\\n"',
            '    ".balign 4\\n"',
            f'    ".global {blob["symbol"]}\\n"',
            f'    "{blob["symbol"]}:\\n"',
            f'    ".incbin \\"{bin_path}\\"\\n"',
            f'    ".size {blob["symbol"]}, {size}\\n"',
            '    ".previous\\n");',
        ]
    open(os.path.join(output_dir, 'extracted_data.c'), 'w', newline='\n').write('\n'.join(lines) + '\n')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--version', default='0004000000086300')
    ap.add_argument('--check', action='store_true', help='only check the declarations against the list')
    ap.add_argument('--output-dir', help='write the blobs and extracted_data.c here')
    a = ap.parse_args()
    blobs = load_blobs(a.version)
    errors = check(blobs)
    for e in errors:
        print('error:', e)
    if errors:
        sys.exit(1)
    if a.output_dir:
        extract(blobs, a.version, a.output_dir)
        print(f'extracted {len(blobs)} blob(s) to {a.output_dir}')
    else:
        print(f'{len(blobs)} blob(s), every extern declaration is listed')


if __name__ == '__main__':
    main()
