#!/usr/bin/env python3
"""Generate the linker script for code.elf.

    python tools/decomp/gen_ldscript.py --version 0004000000086300 -o build/code.ld

The memory layout (.text / .rodata / .data / .bss addresses) is taken from the original
orig/<version>/code.elf. Every known mangled symbol (config/<version>/inputs/symbols_us*.txt)
is provided at its original address (PROVIDE: only used when no object defines the symbol), so
code that is not decompiled yet can still be referenced.
"""
import argparse, glob, os, re, struct

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', '..'))


def segments(elf):
    d = open(elf, 'rb').read()
    phoff = struct.unpack_from('<I', d, 0x1c)[0]
    phsz, phn = struct.unpack_from('<HH', d, 0x2a)
    out = []
    for i in range(phn):
        t, off, va, pa, fsz, msz, fl, al = struct.unpack_from('<8I', d, phoff + i * phsz)
        if t == 1:
            out.append((va, fsz, msz, fl))
    return out


# ARMCC C++ runtime objects inside code.bin that compiled code refers to.
# vtables of the RTTI classes: vptr - 8 (vptrs found by tools/analysis/rtti.py, USA 1.5)
RUNTIME_SYMBOLS = {
    '0004000000086300': {
        '_ZTVN10__cxxabiv117__class_type_infoE': 0x008FAADC,
        '_ZTVN10__cxxabiv120__si_class_type_infoE': 0x008FAAEC,
        '_ZTVN10__cxxabiv121__vmi_class_type_infoE': 0x008FAAFC,
    },
}


def known_symbols(version):
    syms = dict(RUNTIME_SYMBOLS.get(version, {}))
    for p in sorted(glob.glob(os.path.join(ROOT, 'config', version, 'inputs', 'symbols_us*.txt'))):
        for line in open(p, encoding='utf-8', errors='replace'):
            m = re.match(r'\s*(\S+)\s*=\s*(0x[0-9a-fA-F]+)\s*;', line)
            if m:
                syms.setdefault(m.group(1), int(m.group(2), 16))
    return syms


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--version', default='0004000000086300')
    ap.add_argument('-o', '--output', required=True)
    a = ap.parse_args()
    segs = segments(os.path.join(ROOT, 'orig', a.version, 'code.elf'))
    text = next(s for s in segs if s[3] & 1)
    ro = next(s for s in segs if s[3] == 4)
    rw = [s for s in segs if s[3] == 6]
    data = min(rw, key=lambda s: s[0])
    syms = known_symbols(a.version)
    os.makedirs(os.path.dirname(os.path.abspath(a.output)), exist_ok=True)

    out = [f'/* code.elf of ACNL {a.version} - generated by tools/decomp/gen_ldscript.py */',
               'SECTIONS', '{',
           f'    . = 0x{text[0]:08X};',
           '    .text : { *(.crt0) *(.text .text.*) }',
           f'    . = 0x{ro[0]:08X};',
           '    .rodata : { *(.rodata .rodata.*) *(.ARM.exidx*) }',
           f'    . = 0x{data[0]:08X};',
           '    .data : { *(.data .data.*) }',
           '    .bss : { *(.bss .bss.*) *(COMMON) }',
           '    /DISCARD/ : { *(.comment) *(.ARM.attributes) }',
           '}', '', '/* symbols of code that is not decompiled yet */']
    out += [f'PROVIDE({n} = 0x{v:08X});' for n, v in sorted(syms.items(), key=lambda x: x[1])]
    open(a.output, 'w', newline='\n').write('\n'.join(out) + '\n')
    print('wrote', a.output, f'({len(syms)} symbols)')


if __name__ == '__main__':
    main()
