#pragma once

#include "decomp.h"

namespace nw {
namespace gfx {
namespace internal {
void NWCopyVec4Reverse(float*, const float*); // 0x0014E1F0 | nintendogs:bytes [tier A]
void NWCopyVec4WithHeader(float*, const float*, unsigned); // 0x0014E208 | nintendogs:bytes [tier A]
void NWCopyMtx24Reverse(float*, const float*); // 0x0014E224 | nintendogs:bytes [tier A]
void NWCopyMtx24WithHeader(float*, const float*, unsigned); // 0x0014E24C | nintendogs:bytes [tier A]
void NWCopyMtx34Reverse(float*, const float*); // 0x0014E278 | nintendogs:bytes [tier A]
void NWCopyMtx34WithHeader(float*, const float*, unsigned); // 0x0014E2B0 | nintendogs:callgraph [tier A]
void NWCopyMtx44Reverse(float*, const float*); // 0x0014E2EC | nintendogs:bytes [tier A]
void NWCopyMtx44WithHeader(float*, const float*, unsigned); // 0x0014E334 | nintendogs:callgraph [tier A]
void NWCopyVec3Reverse(float*, const float*); // 0x0014E380 | nintendogs:bytes [tier A]
void NWCopyVec3WithHeader(float*, const float*, unsigned); // 0x0014E39C | nintendogs:bytes [tier A]
void NWCopyMtx23Reverse(float*, const float*); // 0x0014E3BC | nintendogs:bytes [tier A]
void NWCopyMtx23WithHeader(float*, const float*, unsigned); // 0x0014E3E8 | nintendogs:bytes [tier A]
void NWCopyMtx33Reverse(float*, const float*); // 0x0014E418 | nintendogs:bytes [tier A]
void NWCopyMtx33WithHeader(float*, const float*, unsigned); // 0x0014E454 | nintendogs:bytes [tier A]
void NWCopyMtx43Reverse(float*, const float*); // 0x0014E494 | nintendogs:bytes [tier A]
void NWCopyMtx43WithHeader(float*, const float*, unsigned); // 0x0014E4E0 | nintendogs:bytes [tier A]
void NWCopyVec2Reverse(float*, const float*); // 0x0014E530 | nintendogs:bytes [tier A]
void NWCopyVec2WithHeader(float*, const float*, unsigned); // 0x0014E54C | nintendogs:bytes [tier A]
void NWCopyMtx22Reverse(float*, const float*); // 0x0014E56C | nintendogs:bytes [tier A]
void NWCopyMtx22WithHeader(float*, const float*, unsigned); // 0x0014E598 | nintendogs:bytes [tier A]
void NWCopyMtx32Reverse(float*, const float*); // 0x0014E5C8 | nintendogs:bytes [tier A]
void NWCopyMtx32WithHeader(float*, const float*, unsigned); // 0x0014E604 | nintendogs:bytes [tier A]
void NWCopyMtx42Reverse(float*, const float*); // 0x0014E644 | nintendogs:bytes [tier A]
void NWCopyMtx42WithHeader(float*, const float*, unsigned); // 0x0014E690 | nintendogs:bytes [tier A]
void NWCopyVec1Reverse(float*, const float*); // 0x0014E6E0 | nintendogs:bytes [tier A]
void NWCopyVec1WithHeader(float*, const float*, unsigned); // 0x0014E6FC | nintendogs:bytes [tier A]
void NWCopyMtx21Reverse(float*, const float*); // 0x0014E71C | nintendogs:bytes [tier A]
void NWCopyMtx21WithHeader(float*, const float*, unsigned); // 0x0014E748 | nintendogs:bytes [tier A]
void NWCopyMtx31Reverse(float*, const float*); // 0x0014E778 | nintendogs:bytes [tier A]
void NWCopyMtx31WithHeader(float*, const float*, unsigned); // 0x0014E7B4 | nintendogs:bytes [tier A]
void NWCopyMtx41Reverse(float*, const float*); // 0x0014E7F4 | nintendogs:bytes [tier A]
void NWCopyMtx41WithHeader(float*, const float*, unsigned); // 0x0014E840 | nintendogs:bytes [tier A]
void FastWordCopyAsm_4(unsigned*, unsigned*); // 0x0014E8AC | nintendogs:bytes [tier A]
void FastWordCopyAsm_6(unsigned*, unsigned*); // 0x0014E8C8 | nintendogs:bytes [tier A]
void FastWordCopyAsm_8(unsigned*, unsigned*); // 0x0014E8E4 | nintendogs:bytes [tier A]
void FastWordCopyAsm_10(unsigned*, unsigned*); // 0x0014E904 | nintendogs:bytes [tier A]
void FastWordCopyAsm_12(unsigned*, unsigned*); // 0x0014E934 | nintendogs:bytes [tier A]
void FastWordCopyAsm_14(unsigned*, unsigned*); // 0x0014E964 | nintendogs:bytes [tier A]
void FastWordCopyAsm_16(unsigned*, unsigned*); // 0x0014E994 | nintendogs:bytes [tier A]
void FastWordCopyAsm_18(unsigned*, unsigned*); // 0x0014E9C8 | nintendogs:bytes [tier A]
void FastWordCopyAsm_20(unsigned*, unsigned*); // 0x0014EA0C | nintendogs:bytes [tier A]
void FastWordCopyAsm_22(unsigned*, unsigned*); // 0x0014EA50 | nintendogs:bytes [tier A]
void FastWordCopyAsm_24(unsigned*, unsigned*); // 0x0014EA94 | nintendogs:bytes [tier A]
void FastWordCopyAsm_26(unsigned*, unsigned*); // 0x0014EADC | nintendogs:bytes [tier A]
void FastWordCopyAsm_28(unsigned*, unsigned*); // 0x0014EB34 | nintendogs:bytes [tier A]
void FastWordCopyAsm_30(unsigned*, unsigned*); // 0x0014EB8C | nintendogs:bytes [tier A]
void FastWordCopyAsm_32(unsigned*, unsigned*); // 0x0014EBE4 | nintendogs:bytes [tier A]
void FastWordCopyAsm_34(unsigned*, unsigned*); // 0x0014EC40 | nintendogs:bytes [tier A]
void FastWordCopyAsm_36(unsigned*, unsigned*); // 0x0014ECAC | nintendogs:bytes [tier A]
void FastWordCopyAsm_38(unsigned*, unsigned*); // 0x0014ED18 | nintendogs:bytes [tier A]
void FastWordCopyAsm_78(unsigned*, unsigned*); // 0x0014ED84 | nintendogs:bytes [tier A]
void ClearVertexAttribute(); // 0x004B22E4 | nintendogs:bytes [tier A]
void SetupShaderProgramMode(bool); // 0x004B2314 | nintendogs:bytes [tier A]
void SetupDrawIndexStreamCommand(nw::gfx::internal::CommandBufferInfo&, nw::gfx::res::ResIndexStream, bool); // 0x004B23D8 | nintendogs:bytes [tier A]
void SetupDeactivateVertexAttributeCommand(nw::gfx::internal::CommandBufferInfo&, nw::gfx::res::ResSeparateDataShape, nw::gfx::res::ResShaderProgramDescription); // 0x004B25E0 | nintendogs:bytes-fuzzy [tier A]
void SetupVertexAttributeCommand(nw::gfx::internal::CommandBufferInfo&, nw::gfx::res::ResSeparateDataShape, nw::gfx::res::ResShaderProgramDescription); // 0x007E6F70 | nintendogs:bytes [tier A]
} // namespace internal
} // namespace gfx
} // namespace nw
